### PR TITLE
Add docstring rules to Ruff linting configuration

### PR DESCRIPTION
**Pull request by xiomaraR**
## Description

This pull request aims to enforce docstring configuration rules for public modules, classes, and methods in the project.

## Commit type

- `chore`

## Issue

This pull request addresses [#136 ](https://github.com/AntonioMrtz/SpotifyElectron/issues/136)

## Solution

The solution involves modifying the lint section in the `Backend/ruff.toml` file to include docstring configuration rules for public modules, classes, and methods.

## Proposed Changes

- Added docstring configuration rules to `Backend/ruff.toml`:
  - D100
  - D101
  - D102
  - D103
  - D104
  - D300
  - D419
- Ignored D100 and D103 on every file included inside the tests/ folder.
- Enforced Google-style docstrings 

## Potential Impact

These changes will improve code readability and maintainability by ensuring consistent documentation standards. Ignoring D100 and D103 in the tests/ folder will prevent linting errors on test files. Enforcing Google-style docstrings will streamline the documentation style.

## Tests Performed
- ruff check . 
- [ ] Test performed

## Screenshots

N/A

## Additional Tasks

N/A

## Assigned

@AntonioMrtz

### CODE REVIEW

**Comment by AntonioMrtz** [comment]
Hi @xiomaraR , Im glad you contributed again, I wasn't sure because i didnt notice u take the issue. It helps me a lot to get track of the tasks state. The PR is good but i think we can expand it a bit if its OK to you. Now that the linter run with the newest rules i think we can make minor adjustments. 

* Ignore D100 and D103 on every file included inside `tests/` folder. See [1](https://docs.astral.sh/ruff/settings/#lint_extend-per-file-ignores),[2](https://github.com/astral-sh/ruff/issues/8795) for more info. 
* I will colaborate on the branch by making docs for every module

**Comment by xiomaraR** [comment]
Ok, good to know. I assumed you'd be notified that I assigned myself. I'll leave a comment next time. I'll work on the new tasks soon!

**Comment by AntonioMrtz** [comment]
No worries with package docs, mainly I want to do them by myself so I can represent exactly what was the original purpose of the package according to the app architecture. It will be a bit hard to make docs of some of the already existing packages. Tho I appreciate your willingness to help :).

**Comment by AntonioMrtz** [comment]
If you dont mind I will be pushing module docs to your forked repo so we can unify the PR content and work on the same branch.

**Comment by AntonioMrtz** [comment]
Hi @xiomaraR , package level missing docs are already pushed. The only remaining thing will be exclude the mentioned rules in tests modules

**Comment by AntonioMrtz** [comment]
All good @xiomaraR , thanks for another contribution. If you want to dig deeper into the project i could suggest issue #129.

**Review by AntonioMrtz — APPROVED** [review]

**Pull request merged**
