### PR TITLE
refactor/Improve-Backend-Validation

### PR DESCRIPTION
**Pull request by aarshgupta24**
## Description

Backend validation was inconsistent in the aspect of naming 

## Commit type

Refactor 

## Issue

Validation methods that are named handle, to make all validations method consistent on both behaviour and syntax.

## Solution

Rename validations using the same pattern (validate_ ) and ensure the structure and behaviour is consistent.

## Proposed Changes

-   handle_playlist_create    ---->   validate_playlist_create
-   handle_playlist_delete_count    ---->    validate_playlist_delete_count  
-   handle_playlist_exists     ---->   validate_playlist_exists
-   handle_playlist_update   ---->   validate_playlist_update
-   handle_song_create  ---->  validate_base_song_create
-   handle_song_exists  ---->  validate_song_exists
-   handle_song_create  ----> validate_song_create

## Potential Impact

Reduces the inconsistency in validation task 

## Assigned

@AntonioMrtz

### CODE REVIEW

**Review by AntonioMrtz — APPROVED** [review]

**Comment by AntonioMrtz** [comment]
@aarshgupta24 Check Ruff formatting and linting. More info [here](https://antoniomrtz.github.io/SpotifyElectron/backend/Linting-%26-Formatting/)

**Comment by AntonioMrtz** [comment]
@aarshgupta24 Backend Tests fail because no enviroments are provided to github actions from forked repos.

**Comment by aarshgupta24** [comment]
so i have to do this ruff formatting only?

**Comment by AntonioMrtz** [comment]
> so i have to do this ruff formatting only?

Yes 😀

**Comment by AntonioMrtz** [comment]
Thanks for contributing @aarshgupta24 😀. Merging the PR

**Pull request merged**
