### PR TITLE
#268: Create context for reloading sidebar data

### PR DESCRIPTION
**Pull request by yashwanthvarma18**
## Description

This pull request introduces a new context for managing sidebar data across the application. The goal is to streamline the refresh of sidebar data by avoiding prop drilling and making the refreshSidebarData method accessible from any component in the app.

## Commit type

feat

## Issue
#268 
The current implementation requires prop drilling to access the refreshSidebarData method in various components, making the codebase cumbersome and less maintainable.

## Solution

We have created a context that provides the refreshSidebarData method, allowing any component to access it directly without passing it through several layers of components.

## Proposed Changes

1. Created a new context for sidebar data management.
2. Updated the App.tsx component to supply the refreshSidebarData method to the context provider.
3. Refactored existing components to use the new context instead of prop drilling for accessing refreshSidebarData.

## Potential Impact

These changes will enhance the maintainability of the application by reducing the complexity of prop passing. There is a potential for minor adjustments needed in components that previously relied on direct props, but it improves the overall structure and accessibility of the sidebar data functionality.

## Additional Tasks

1. Update documentation to reflect the new context usage.
2. Additional testing may be required to ensure that components correctly consume the context.

## Assigned

@AntonioMrtz

### CODE REVIEW

**Comment by yashwanthvarma18** [comment]
@AntonioMrtz  Could you please review my pull request and merge it? I'm a beginner and have done my best to deliver.

Thank you!

**Comment by AntonioMrtz** [comment]
Hi @yashwanthvarma18 , thanks for your work, I will try to review it ASAP :) . We have a list of contributors in `Readme.md` and `Contributors.md`, feel free to add yourself keeping the format and commit the changes :)

**Comment by yashwanthvarma18** [comment]
@AntonioMrtz 
I am not familiar with what these issues means and caused due to 
Please let me know how to resolve them 
ESlint Check / run-frontend-lint (pull_request) 
Frontend Style Prettier / run-frontend-style-check (pull_request) 
Frontend Tests / frontend-test (pull_request)

**Comment by AntonioMrtz** [comment]
> @AntonioMrtz I am not familiar with what these issues means and caused due to Please let me know how to resolve them ESlint Check / run-frontend-lint (pull_request) Frontend Style Prettier / run-frontend-style-check (pull_request) Frontend Tests / frontend-test (pull_request)

If you go inside details for each failed pipeline you can see the error logs. To reproduce it locally run the follow commands:

* Prettier: `npm run format:write`. Pipeline checks styling is correct
* Lint: `npm run lint`. Check linting rules
* Tests: `npm run tests`. Tests are failing because of the modifications

**Comment by yashwanthvarma18** [comment]
@AntonioMrtz what can i do to correct this 
Check OpenAPI schema is updated / check-openapi-schema-is-updated (pull_request) Failing after 1m

**Comment by yashwanthvarma18** [comment]
@AntonioMrtz Please check the new commit and let me know if there is any issue again

**Comment by AntonioMrtz** [comment]
Hi @yashwanthvarma18 , just a few things:

I know it probably took some time to do the adjustments but we don't want all the external .erb packages, markdown doc files and more to use frontend prettier format. Also I found that many rules that we don't use are being applied. I'm confident to say that this can be due to running `npm run` commands in an incorrect directory or that these commands didn't follow the ruleset they have as input

As you can see here, the custom commands that run with `npm run` have parameters that affect the output such as file to be ignored and the rules to be applied.
```json
"scripts": {
    "lint": "cross-env NODE_ENV=development eslint src/ --ext .js,.jsx,.ts,.tsx --fix",
    "format:write": "prettier src/ --write --ignore-path .prettierignore",
}
```

Example with `npm run format:write`: only `src/` files will be formatted and it will honor .prettierignore rules

What would I do:

* Revert back to commit `89e47c85b53a5e12749f56045ef3ed5b5e520b62`
* Run the the commands I mentioned in previous message while being in the directory `Electron/` and making sure the command rules are being honored
* Make the adjustments that the commands output, there won't be a lot, it will only output warnings about code that YOU changed, the actual codebase passes the pipelines with no adjusments
* I will review the provided code :)

Let me know if you have any question, code looked good but I cannot merge a lot of modified files that were out of scope for this task :)

**Comment by yashwanthvarma18** [comment]
@AntonioMrtz 
I spent most of the day working on this, and I understand that you're not satisfied with the PR. That's fine—I hope the code I pushed can still be helpful to you in some way. Thanks for the opportunity!

**Comment by AntonioMrtz** [comment]
> @AntonioMrtz I spent most of the day working on this, and I understand that you're not satisfied with the PR. That's fine—I hope the code I pushed can still be helpful to you in some way. Thanks for the opportunity!

Yeah, I checked the changes and know they have took a long time to implement. Sorry :( , we have to keep the codebase with the same style and format

**Comment by AntonioMrtz** [comment]
Hi @yashwanthvarma18  are you still working in this issue :) ? If you need help with something just let me know 🖐️

**Pull request closed without merging**
